In [ ]:
# Last Technique for Data Preprocessing usinh Mean and Median
# 9th interview:
# why mean and median arre used in data preprocessing?
# and; mean and median always working with numerical data
# mean and median always working in data preprocessing for Nah value not for 0

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "age": [20,21,np.nan,22,23],
    "marks": [80,90,np.nan,75,np.nan]
}
df = pd.DataFrame(data)
df

    age  marks
0  20.0   80.0
1  21.0   90.0
2   NaN    NaN
3  22.0   75.0
4  23.0    NaN

In [ ]:
df["age"]=df["age"].mean()
df

    age  marks
0  21.5   80.0
1  21.5   90.0
2  21.5    NaN
3  21.5   75.0
4  21.5    NaN

In [8]:
df["age"]=df["age"].median()
df

    age  marks
0  21.5   80.0
1  21.5   90.0
2  21.5    NaN
3  21.5   75.0
4  21.5    NaN

In [9]:
df["marks"]=df["marks"].median()
df

    age  marks
0  21.5   80.0
1  21.5   80.0
2  21.5   80.0
3  21.5   80.0
4  21.5   80.0

In [6]:
# 30 records with missing value Nan

In [7]:
import numpy as np
import pandas as pd

In [11]:
data = {
    "phy": [78, 65, 89, np.nan, 72, 55, 91, 68, 84, 76,
            63, np.nan, 88, 70, 95, 61, 73, 82, np.nan, 67,
            79, 58, 86, 74, 92, np.nan, 69, 81, 77, 64],

    "chem": [82, 71, np.nan, 68, 75, 59, 94, 72, 87, np.nan,
             65, 78, 90, 73, 96, 62, np.nan, 85, 69, 74,
             81, 60, 88, 76, np.nan, 70, 67, 83, 79, 66],

    "math": [91, 68, 85, 74, np.nan, 62, 96, 71, 89, 78,
             65, np.nan, 93, 80, 97, 59, 76, 84, 70, 73,
             88, 61, np.nan, 79, 94, 72, 67, 86, 81, 69],

    "bio": [75, 82, 88, 69, 73, np.nan, 91, 77, 85, 80,
            64, 71, np.nan, 76, 94, 68, 79, 87, 72, 65,
            83, 60, 89, np.nan, 92, 74, 66, 81, 78, 70],

    "english": [80, 74, 91, 68, 77, 62, np.nan, 85, 89, 73,
                66, 79, 88, np.nan, 95, 70, 76, 84, 69, 72,
                81, 63, 90, 78, np.nan, 75, 68, 86, 79, 71]
}

df = pd.DataFrame(data)
df

     phy  chem  math   bio  english
0   78.0  82.0  91.0  75.0     80.0
1   65.0  71.0  68.0  82.0     74.0
2   89.0   NaN  85.0  88.0     91.0
3    NaN  68.0  74.0  69.0     68.0
4   72.0  75.0   NaN  73.0     77.0
5   55.0  59.0  62.0   NaN     62.0
6   91.0  94.0  96.0  91.0      NaN
7   68.0  72.0  71.0  77.0     85.0
8   84.0  87.0  89.0  85.0     89.0
9   76.0   NaN  78.0  80.0     73.0
10  63.0  65.0  65.0  64.0     66.0
11   NaN  78.0   NaN  71.0     79.0
12  88.0  90.0  93.0   NaN     88.0
13  70.0  73.0  80.0  76.0      NaN
14  95.0  96.0  97.0  94.0     95.0
15  61.0  62.0  59.0  68.0     70.0
16  73.0   NaN  76.0  79.0     76.0
17  82.0  85.0  84.0  87.0     84.0
18   NaN  69.0  70.0  72.0     69.0
19  67.0  74.0  73.0  65.0     72.0
20  79.0  81.0  88.0  83.0     81.0
21  58.0  60.0  61.0  60.0     63.0
22  86.0  88.0   NaN  89.0     90.0
23  74.0  76.0  79.0   NaN     78.0
24  92.0   NaN  94.0  92.0      NaN
25   NaN  70.0  72.0  74.0     75.0
26  69.0  67.0  67.0  66.0     68.0
27  81.0  83.0  86.0  81.0     86.0
28  77.0  79.0  81.0  78.0     79.0
29  64.0  66.0  69.0  70.0     71.0

In [12]:
df["phy"]=df["phy"].mean()
df

          phy  chem  math   bio  english
0   75.269231  82.0  91.0  75.0     80.0
1   75.269231  71.0  68.0  82.0     74.0
2   75.269231   NaN  85.0  88.0     91.0
3   75.269231  68.0  74.0  69.0     68.0
4   75.269231  75.0   NaN  73.0     77.0
5   75.269231  59.0  62.0   NaN     62.0
6   75.269231  94.0  96.0  91.0      NaN
7   75.269231  72.0  71.0  77.0     85.0
8   75.269231  87.0  89.0  85.0     89.0
9   75.269231   NaN  78.0  80.0     73.0
10  75.269231  65.0  65.0  64.0     66.0
11  75.269231  78.0   NaN  71.0     79.0
12  75.269231  90.0  93.0   NaN     88.0
13  75.269231  73.0  80.0  76.0      NaN
14  75.269231  96.0  97.0  94.0     95.0
15  75.269231  62.0  59.0  68.0     70.0
16  75.269231   NaN  76.0  79.0     76.0
17  75.269231  85.0  84.0  87.0     84.0
18  75.269231  69.0  70.0  72.0     69.0
19  75.269231  74.0  73.0  65.0     72.0
20  75.269231  81.0  88.0  83.0     81.0
21  75.269231  60.0  61.0  60.0     63.0
22  75.269231  88.0   NaN  89.0     90.0
23  75.269231  76.0  79.0   NaN     78.0
24  75.269231   NaN  94.0  92.0      NaN
25  75.269231  70.0  72.0  74.0     75.0
26  75.269231  67.0  67.0  66.0     68.0
27  75.269231  83.0  86.0  81.0     86.0
28  75.269231  79.0  81.0  78.0     79.0
29  75.269231  66.0  69.0  70.0     71.0

In [ ]:
df