In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("86.student_marks_30_records_missing.csv")
df

,Student_ID,Name,Mathematics,Physics,Chemistry,English,Computer_Science
0,1,Student_1,86.0,37.0,48.0,82.0,76.0
1,2,Student_2,49.0,85.0,82.0,57.0,79.0
2,3,Student_3,NaN,41.0,49.0,96.0,96.0
3,4,Student_4,55.0,55.0,96.0,71.0,91.0
4,5,Student_5,58.0,73.0,74.0,78.0,40.0
5,6,Student_6,37.0,NaN,87.0,69.0,62.0
6,7,Student_7,56.0,38.0,58.0,99.0,62.0
7,8,Student_8,87.0,94.0,60.0,81.0,78.0
8,9,Student_9,36.0,48.0,NaN,37.0,64.0
9,10,Student_10,64.0,43.0,75.0,35.0,96.0
10,11,Student_11,72.0,87.0,63.0,39.0,96.0
11,12,Student_12,36.0,36.0,49.0,NaN,35.0
12,13,Student_13,98.0,94.0,79.0,61.0,61.0
13,14,Student_14,94.0,78.0,99.0,43.0,96.0
14,15,Student_15,55.0,42.0,43.0,49.0,NaN
15,16,Student_16,67.0,81.0,35.0,76.0,61.0
16,17,Student_17,92.0,69.0,42.0,85.0,43.0
17,18,Student_18,NaN,70.0,97.0,97.0,96.0
18,19,Student_19,83.0,84.0,45.0,86.0,71.0
19,20,Student_20,93.0,38.0,42.0,NaN,85.0
20,21,Student_21,76.0,36.0,69.0,57.0,78.0
21,22,Student_22,94.0,40.0,69.0,49.0,58.0
22,23,Student_23,49.0,88.0,67.0,77.0,93.0
23,24,Student_24,96.0,NaN,39.0,63.0,66.0
24,25,Student_25,96.0,88.0,75.0,70.0,86.0
25,26,Student_26,81.0,97.0,62.0,47.0,NaN
26,27,Student_27,96.0,52.0,41.0,66.0,92.0
27,28,Student_28,85.0,78.0,NaN,93.0,86.0
28,29,Student_29,89.0,68.0,68.0,62.0,46.0
29,30,Student_30,98.0,96.0,67.0,100.0,73.0

In [5]:
df.mean(numeric_only=True)
df

,Student_ID,Name,Mathematics,Physics,Chemistry,English,Computer_Science
0,1,Student_1,86.0,37.0,48.0,82.0,76.0
1,2,Student_2,49.0,85.0,82.0,57.0,79.0
2,3,Student_3,NaN,41.0,49.0,96.0,96.0
3,4,Student_4,55.0,55.0,96.0,71.0,91.0
4,5,Student_5,58.0,73.0,74.0,78.0,40.0
5,6,Student_6,37.0,NaN,87.0,69.0,62.0
6,7,Student_7,56.0,38.0,58.0,99.0,62.0
7,8,Student_8,87.0,94.0,60.0,81.0,78.0
8,9,Student_9,36.0,48.0,NaN,37.0,64.0
9,10,Student_10,64.0,43.0,75.0,35.0,96.0
10,11,Student_11,72.0,87.0,63.0,39.0,96.0
11,12,Student_12,36.0,36.0,49.0,NaN,35.0
12,13,Student_13,98.0,94.0,79.0,61.0,61.0
13,14,Student_14,94.0,78.0,99.0,43.0,96.0
14,15,Student_15,55.0,42.0,43.0,49.0,NaN
15,16,Student_16,67.0,81.0,35.0,76.0,61.0
16,17,Student_17,92.0,69.0,42.0,85.0,43.0
17,18,Student_18,NaN,70.0,97.0,97.0,96.0
18,19,Student_19,83.0,84.0,45.0,86.0,71.0
19,20,Student_20,93.0,38.0,42.0,NaN,85.0
20,21,Student_21,76.0,36.0,69.0,57.0,78.0
21,22,Student_22,94.0,40.0,69.0,49.0,58.0
22,23,Student_23,49.0,88.0,67.0,77.0,93.0
23,24,Student_24,96.0,NaN,39.0,63.0,66.0
24,25,Student_25,96.0,88.0,75.0,70.0,86.0
25,26,Student_26,81.0,97.0,62.0,47.0,NaN
26,27,Student_27,96.0,52.0,41.0,66.0,92.0
27,28,Student_28,85.0,78.0,NaN,93.0,86.0
28,29,Student_29,89.0,68.0,68.0,62.0,46.0
29,30,Student_30,98.0,96.0,67.0,100.0,73.0

In [6]:
df.median(numeric_only=True)
df

,Student_ID,Name,Mathematics,Physics,Chemistry,English,Computer_Science
0,1,Student_1,86.0,37.0,48.0,82.0,76.0
1,2,Student_2,49.0,85.0,82.0,57.0,79.0
2,3,Student_3,NaN,41.0,49.0,96.0,96.0
3,4,Student_4,55.0,55.0,96.0,71.0,91.0
4,5,Student_5,58.0,73.0,74.0,78.0,40.0
5,6,Student_6,37.0,NaN,87.0,69.0,62.0
6,7,Student_7,56.0,38.0,58.0,99.0,62.0
7,8,Student_8,87.0,94.0,60.0,81.0,78.0
8,9,Student_9,36.0,48.0,NaN,37.0,64.0
9,10,Student_10,64.0,43.0,75.0,35.0,96.0
10,11,Student_11,72.0,87.0,63.0,39.0,96.0
11,12,Student_12,36.0,36.0,49.0,NaN,35.0
12,13,Student_13,98.0,94.0,79.0,61.0,61.0
13,14,Student_14,94.0,78.0,99.0,43.0,96.0
14,15,Student_15,55.0,42.0,43.0,49.0,NaN
15,16,Student_16,67.0,81.0,35.0,76.0,61.0
16,17,Student_17,92.0,69.0,42.0,85.0,43.0
17,18,Student_18,NaN,70.0,97.0,97.0,96.0
18,19,Student_19,83.0,84.0,45.0,86.0,71.0
19,20,Student_20,93.0,38.0,42.0,NaN,85.0
20,21,Student_21,76.0,36.0,69.0,57.0,78.0
21,22,Student_22,94.0,40.0,69.0,49.0,58.0
22,23,Student_23,49.0,88.0,67.0,77.0,93.0
23,24,Student_24,96.0,NaN,39.0,63.0,66.0
24,25,Student_25,96.0,88.0,75.0,70.0,86.0
25,26,Student_26,81.0,97.0,62.0,47.0,NaN
26,27,Student_27,96.0,52.0,41.0,66.0,92.0
27,28,Student_28,85.0,78.0,NaN,93.0,86.0
28,29,Student_29,89.0,68.0,68.0,62.0,46.0
29,30,Student_30,98.0,96.0,67.0,100.0,73.0