In [ ]:
# underfitting and overfitting   ---> Interview must assk this question to you
# L1 and L2 Regularlization
# Bias and Variance
# Ridge and Lasso Regression
# File tunning

In [ ]:
# There are multiple problem in ML 
# 1. Regression Problem
# 2.classification problem
# 3. cluster problem

# we can solve ML problem using this
# but there are TWO MAIN error in ML underfitting and overfitting
# =>when generates
# when model are tries to learn from data

# 1. underfiting :- poor performance on both training and testing data
# 2. overfitting :- when model are well performed on training but poor performance on new test data.
# 3. balance fit :- model training and testing : better performance.
# when the model is more complez then low biased if the model is simple then high biased.
# if the model is less complex the variance will be low if the model is more complex the variance will be high.
# if the model is less complex it will tell the errors if the model is high complex it will tell the total errors.
# with the help of trade off we can solve bias and variance problem
# Bias-Variance Tradeoff:
# - High Bias: Underfitting (model is too simple)
# - High Variance: Overfitting (model is too complex)
# - Goal: Find the optimal balance where both bias and variance are minimized.
# To address overfitting, we can use techniques like:
# - Cross-validation
# - Regularization (L1/L2)
# - Pruning (for decision trees)
# - Early stopping
# - Increasing training data size
# Que. When Bias gegnerate ?
# Ans. When number of features are less and model aree too simple 
# Que. When Variance generate ?
# Ans. When number of features are more and model are too complex then variance concept come into the features.
# Summary:
# Bias: Error due to erroneous assumptions in the learning algorithm.
# Variance: Error due to sensitivity to small fluctuations in the training set.
# The goal is to achieve low bias and low variance for the best generalization.

# with the help of Regularization method we can both problems
# There are two Regularization
# 1. L1 Regularization (Lasso)
# 2. L2 Regularization (Ridge)
# Both are reduce error
# # L1 Regularization (Lasso) adds a penalty equal to the absolute value of the magnitude of coefficients.
# L2 Regularization (Ridge) adds a penalty equal to the square of the magnitude of coefficients.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml
boston = fetch_openml(name="boston",version=1,as_frame=True,parser="pandas")

In [5]:
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
 0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
 1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
 2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
 3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
 4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
 ..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
 501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
 502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
 503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
 504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
 505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
 0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
 1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
 2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
 3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
 4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
 ..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
 501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
 502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
 503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
 504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
 505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [6]:
df = boston.frame
df

        CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

[506 rows x 14 columns]

In [7]:
df.sample()

        CRIM   ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
121  0.07165  0.0  25.65    0  0.581  ...  188.0     19.1  377.67  14.27  20.3

[1 rows x 14 columns]

In [8]:
df["price"]=boston.target

In [9]:
df.sample()

        CRIM   ZN  INDUS CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  price
474  8.05579  0.0   18.1    0  0.584  ...     20.2  352.58  18.14  13.8   13.8

[1 rows x 15 columns]

In [10]:
# EDA
df.shape

(506, 15)

In [11]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV', 'price'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
 14  price    506 non-null    float64
dtypes: category(2), float64(13)
memory usage: 52.6 KB

In [14]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
price      0
dtype: int64

In [15]:
df.corr()

             CRIM        ZN     INDUS  ...     LSTAT      MEDV     price
CRIM     1.000000 -0.200469  0.406583  ...  0.455621 -0.388305 -0.388305
ZN      -0.200469  1.000000 -0.533828  ... -0.412995  0.360445  0.360445
INDUS    0.406583 -0.533828  1.000000  ...  0.603800 -0.483725 -0.483725
CHAS    -0.055892 -0.042697  0.062938  ... -0.053929  0.175260  0.175260
NOX      0.420972 -0.516604  0.763651  ...  0.590879 -0.427321 -0.427321
RM      -0.219247  0.311991 -0.391676  ... -0.613808  0.695360  0.695360
AGE      0.352734 -0.569537  0.644779  ...  0.602339 -0.376955 -0.376955
DIS     -0.379670  0.664408 -0.708027  ... -0.496996  0.249929  0.249929
RAD      0.625505 -0.311948  0.595129  ...  0.488676 -0.381626 -0.381626
TAX      0.582764 -0.314563  0.720760  ...  0.543993 -0.468536 -0.468536
PTRATIO  0.289946 -0.391679  0.383248  ...  0.374044 -0.507787 -0.507787
B       -0.385064  0.175520 -0.356977  ... -0.366087  0.333461  0.333461
LSTAT    0.455621 -0.412995  0.603800  ...  1.000000 -0.737663 -0.737663
MEDV    -0.388305  0.360445 -0.483725  ... -0.737663  1.000000  1.000000
price   -0.388305  0.360445 -0.483725  ... -0.737663  1.000000  1.000000

[15 rows x 15 columns]

In [20]:
# split X and Y
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [21]:
X.head()
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

In [22]:
# if you have categorical data then convert into numeric
# if you have combination of int , float and other then we will convert float 
X = X.astype(float)
y = y.astype(float)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 14)
(102, 14)
(404,)
(102,)

In [ ]:
from sklearn.model_selection import cross_val_score
'''
cross_val_score is used to more model performance in testing time
There are five parts are executes in cross_val_score
4 parts(fold) --- training 1 part(fold) --- testing
are called 5 fold --- cross validation
1. Estimator (model)
2. X (features)
3. y (target)
4. cv (number of folds)
5. scoring (metric)


model = LinearRegression()  ---> Model trained only once
'''
from sklearn.tree import DecisionTreeClassifier